server {
    listen 8080 default_server;
    listen [::]:8080 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types application/javascript application/json text/css text/html text/plain image/svg+xml;
    gzip_min_length 1024;
}
